### ISSUE TITLE
Container exits with code 1

### ISSUE THREAD

**Issue by GoodOldTos** [Just5KY/honeypots#81]
Hi,
not sure why but when I use the following docker-compose file, container starts but exits quickly with code 1:

[docker-compose.yml.txt](https://github.com/user-attachments/files/16116820/docker-compose.yml.txt)

Docker logs are:
[INFO] For updates, check https://github.com/qeeqbox/honeypots
[INFO] Use [Enter] to exit or python3 -m honeypots --kill
[WARNING] config.json file overrides --ip, --port, --username and --password
[INFO] Parsing honeypot [normal]
[INFO] servers mysql running...
[INFO] Everything looks good!
[INFO] [x] Cleaning

I don't understand the warning about config.json as there is no such file.
I modified a little bit the compose file to understand the failure (restart:no, restricted to mysql) but no luck.
mysl.log is created in /mnt/xdata/docker_data/bck/honeypots/logs but is 0 byte long.
Any clue?
Thanks,
Jean

**Comment by just5ky** [comment]
Will take a look

config.json is the config file that I am putting inside the docker container, you can check it here
https://github.com/just5ky/honeypots/blob/latest/config.json

You can replace the config file and put in your own.
Just add it to the volume like:

```yml
        volumes:
            - 'config.json:/honeypots/config.json'
```

**Comment by just5ky** [comment]
Got it to work @GoodOldTos 
need to add `stdin_open: true` also updated the README file, thanks.

The log file will be 0 bytes till someone triggers the honeypot.

```yml
services:
    honeypots:
        container_name: honeypots
        image: justsky/honeypots:latest
        stdin_open: true
        command: --setup mysql --verbose --auto
        volumes:
            - './logs:/honeypots/logs'
        ports:
            - 20022:22         # SSH
            - 23306:3306     # MYSQL
```

```log
╰─❯ docker compose up --remove-orphans
[+] Running 2/0
 ✔ Container docker-honeypots1-1  Removed                                                                          0.0s
 ✔ Container honeypots            Created                                                                          0.0s
Attaching to honeypots
honeypots  | [INFO] For updates, check https://github.com/qeeqbox/honeypots
honeypots  | [INFO] Use [Enter] to exit or python3 -m honeypots --kill
honeypots  | [WARNING] config.json file overrides --ip, --port, --username and --password
honeypots  | [INFO] Parsing honeypot [normal]
honeypots  | [INFO] servers mysql running...
honeypots  | [INFO] Everything looks good!
```
